package com.perficient.pimentomvc;
// Generated Apr 11, 2014 3:07:03 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name="groups"
    ,catalog="perficient"
)
public class Groups  implements java.io.Serializable {


     private Integer groupId;
     private Broker broker;
     private String groupName;
     private boolean isActive;
     private Set<GroupBenefit> groupBenefits = new HashSet<GroupBenefit>(0);

    public Groups() {
    }

	
    public Groups(Broker broker, String groupName, boolean isActive) {
        this.broker = broker;
        this.groupName = groupName;
        this.isActive = isActive;
    }
    public Groups(Broker broker, String groupName, boolean isActive, Set<GroupBenefit> groupBenefits) {
       this.broker = broker;
       this.groupName = groupName;
       this.isActive = isActive;
       this.groupBenefits = groupBenefits;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="groupId", unique=true, nullable=false)
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brokerId", nullable=false)
    public Broker getBroker() {
        return this.broker;
    }
    
    public void setBroker(Broker broker) {
        this.broker = broker;
    }

    
    @Column(name="groupName", nullable=false)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    
    @Column(name="isActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groups")
    public Set<GroupBenefit> getGroupBenefits() {
        return this.groupBenefits;
    }
    
    public void setGroupBenefits(Set<GroupBenefit> groupBenefits) {
        this.groupBenefits = groupBenefits;
    }




}


