package com.perficient.pimentomvc;
// Generated Apr 11, 2014 3:07:03 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GroupBenefit generated by hbm2java
 */
@Entity
@Table(name="groupBenefit"
    ,catalog="perficient"
)
public class GroupBenefit  implements java.io.Serializable {


     private Integer groupBenefitId;
     private Groups groups;
     private Benefit benefit;
     private boolean isActive;

    public GroupBenefit() {
    }

    public GroupBenefit(Groups groups, Benefit benefit, boolean isActive) {
       this.groups = groups;
       this.benefit = benefit;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="groupBenefitId", unique=true, nullable=false)
    public Integer getGroupBenefitId() {
        return this.groupBenefitId;
    }
    
    public void setGroupBenefitId(Integer groupBenefitId) {
        this.groupBenefitId = groupBenefitId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="groupId", nullable=false)
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="benefitId", nullable=false)
    public Benefit getBenefit() {
        return this.benefit;
    }
    
    public void setBenefit(Benefit benefit) {
        this.benefit = benefit;
    }

    
    @Column(name="isActive", nullable=false)
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


